<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageVersion Include="Syncfusion.Blazor.Buttons" Version="34.2.5" />
    <PackageVersion Include="Syncfusion.Blazor.Navigations" Version="34.2.5" />
    <PackageVersion Include="Syncfusion.Blazor.Themes" Version="34.2.5" />
  </ItemGroup>
</Project>
