<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0cfaeb20-baeb-43e3-8c2d-44de01250f66</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Syncfusion.Blazor.Buttons" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" />
    <PackageReference Include="Syncfusion.Blazor.Grid" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" />
    <PackageReference Include="Syncfusion.Blazor.Kanban" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" />
    <PackageReference Include="Syncfusion.Blazor.Schedule" />
    <PackageReference Include="Syncfusion.Blazor.SfPdfViewer" />
    <PackageReference Include="Syncfusion.Blazor.Themes" />
  </ItemGroup>

</Project>
